spring:
  application:
    name: spring-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yamahar1
    driverClassName: org.postgresql.Driver
#    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
#    username: red
#    password: red
#    driverClassName: oracle.jdbc.OracleDriver
  jpa:
#    database: oracle
    database: postgresql
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
#    database-platform: org.hibernate.dialect.OracleDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    database: postgresql
#    properties:
#      hibernate:
#        boot:
#          allow_jdbc_metadata_access: false

spring-demo:
#    db: ora
  db: postgres